name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y xorg-dev python3-jinja2

      - name: Install Python dependencies
        run: python -m pip install jinja2

      - name: Cache CMake deps
        uses: actions/cache@v3
        with:
          path: build/debug/_deps
          key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-

      - name: Configure
        run: cmake --preset debug

      - name: Build
        run: cmake --build --preset debug

      - name: Test
        run: ctest --preset debug

      - name: Upload sandbox artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sandbox-${{ matrix.os }}
          path: build/debug/samples/sandbox/*
